# Generated by Django 4.1.2 on 2022-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
            ],
        ),
    ]
