# Generated by Django 4.1.2 on 2022-10-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmer',
            new_name='Farmer_Details',
        ),
    ]
